dir: models
name: xgboost
model_path: ${model.dir}/${model.name}.pkl
use_label_encoder: False
objective: "reg:squarederror"
early_stopping_rounds: 20
eval_metric: rmse
device: gpu
tree_method: gpu_hist
seed: 42
n_estimators:
  low: 100
  high: 1000
  q: 10
max_depth: 
  low: 3
  high: 18
  q: 1
gamma:
  low: 1
  high: 9
reg_alpha:
  low: 40
  high: 180
  q: 1
reg_lambda:
  low: 0
  high: 1
colsample_bytree:
  low: 0.5
  high: 1
min_child_weight:
  low: 0
  high: 10
  q: 1