defaults:
  - model: model.yaml

data:
  path: Data/train.csv
  test_path: Data/test.csv
  result_path: Data/result.csv

features:
  onehot_categorical:
    - store_and_fwd_flag
  drop_columns:
    - id
    - pickup_datetime
    - dropoff_datetime
  scale_columns:
    - distance_latitude
    - distance_longitude
    - distance
  onehot_encoded:
    - store_and_fwd_flag_N
    - store_and_fwd_flag_Y


processed:
  dir: Data/processed
  train_x: 
    name: train_x.csv
    path: ${processed.dir}/${processed.train_x.name}
  test_x:
    name: test_x.csv
    path: ${processed.dir}/${processed.test_x.name}
  train_y: 
    name: train_y.csv
    path: ${processed.dir}/${processed.train_y.name}
  test_y:
    name: test_y.csv
    path: ${processed.dir}/${processed.test_y.name} 


mlflow_tracking_uri:
  https://dagshub.com/Ravindu987/Taxi_time_prediction.mlflow
mlflow_USERNAME:
  Ravindu987
mlflow_PASSWORD:
  57801e5becd1deb25a67f916bd7f61b91406a1c7
