# bento_config.yaml
api_server:
  http:
    cors:
      enabled: true
      access_control_allow_origins: ["*"]
      access_control_allow_methods: ["GET", "OPTIONS", "POST", "HEAD", "PUT"]
      access_control_allow_credentials: true
      access_control_allow_headers: ["*"]
      access_control_max_age: 1200
      access_control_expose_headers: ["Content-Length"]
